# Generated by Django 4.2.13 on 2024-06-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoredRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.IntegerField(unique=True)),
                ("monitored", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.IntegerField(unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("repo_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pull_request_state", models.CharField(max_length=100)),
                ("pull_request_id", models.CharField(max_length=100)),
                (
                    "repo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translate.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repo",)},
            },
        ),
        migrations.CreateModel(
            name="MarkdownFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=100)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translate.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repo", "file_name", "file_path")},
            },
        ),
        migrations.CreateModel(
            name="LastCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_id", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "repo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translate.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repo",)},
            },
        ),
    ]
