# Generated by Django 4.2.13 on 2024-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translate", "0004_alter_lastcommit_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="translation_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="lastcommit",
            unique_together={("repo", "commit_id")},
        ),
    ]
